name: AI Task
description: Structured task for Copilot/Workspace/AI agent
labels: ["ai","enhancement"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: One-sentence outcome
    validations: { required: true }
  - type: textarea
    id: context
    attributes:
      label: Context / Background
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Bullet, verifiable checks
    validations: { required: true }
  - type: textarea
    id: plan
    attributes:
      label: Suggested plan (optional)
  - type: dropdown
    id: area
    attributes:
      label: Area
      options: ["contracts","frontend","infra","docs"]
