name: contracts-ci
  
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "contracts/**"
      - ".github/workflows/contracts-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "contracts/**"
      - ".github/workflows/contracts-ci.yml"

concurrency:
  group: contracts-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        node: [20]        # koristimo samo Node 20
    defaults:
      run:
        working-directory: contracts

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node ${{ matrix.node }} + npm cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: |
            contracts/package-lock.json
            contracts/package.json

      # Cache za skinute solc binarije (put je različit po verzijama; navodimo oba)
      - name: Cache solc compilers
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hardhat-nodejs/compilers
            ~/.cache/hardhat/compilers
          key: ${{ runner.os }}-solc-cache-${{ matrix.node }}-v1

      - name: Install
        run: npm ci

      # Retry x3 zbog povremenih timeouta pri preuzimanju solc-a
      - name: Compile (retry)
        run: |
          for i in 1 2 3; do
            npx hardhat compile && s=0 && break || s=$?
            echo "compile failed, retrying in 5s ($i/3)"; sleep 5
          done
          exit $s

      - name: Test
        run: npx hardhat test | tee test-output-node-${{ matrix.node }}.log

      - name: Upload artifacts (build + logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: contracts-artifacts-node-${{ matrix.node }}
          path: |
            contracts/artifacts
            contracts/cache/solidity-files-cache.json
            contracts/test-output-node-${{ matrix.node }}.log
          retention-days: 7
