name: deploy-sepolia
on: { workflow_dispatch: {} }

permissions: { contents: read }

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults: { run: { working-directory: contracts } }
    env:
      SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
      PRIVATE_KEY:     ${{ secrets.PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm, cache-dependency-path: "contracts/package.json" }
      - name: Install
        run: npm install
      - name: Compile
        run: npx hardhat compile
      - name: Deploy
        run: npx hardhat run scripts/deploy.js --network sepolia
